### ISSUE TITLE
Druid missing their two skills and weapon proficiencies

### ISSUE THREAD

**Issue by Merudo** [rtakehara/5e-Framework#19]
**Describe the bug**
Level 1 Druid starts without their two class skills and their weapon proficiencies (clubs, daggers, darts, javelins, maces, quarterstaffs, scimitars, sickles, slings, spears).

**To Reproduce**
1. Create a Druid through the Wizard
2. Notices the Wizard skips the skill selection
3. Once the character is created, notice the lack of any weapon proficiencies

**Expected behavior**
The Druid gets his two skills and the weapon proficiencies

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Merudo** [comment]
Seems like the code wrongly multiclasses druids as `Druid 1/Druid 1` instead of `Druid 1`, and doesn't give them their proficiencies.

**Comment by rtakehara** [comment]
Fixed for the next update, it's not online yet since I am working on other issues, so I am not sure if I should close the issue or not...

**Comment by rtakehara** [comment]
fixed on v2.5
