### ISSUE TITLE
json.get error in form-submitted items

### ISSUE THREAD

**Issue by Rukbat16** [rtakehara/5e-Framework#2]
I have been using the framework to play Dragon of Icespire Keep solo, and test some of the latest UA character options.
For the most part, entering new things from the character sheet works like a charm. But every now and then there is an item that simply refuses to work, and I cannot figure out why.

One such problematic item is the following: sending stones, here it is in JSON format:
{"sending stones":{"description":"*Adventuring Gear*\n400 gp, 5 lb.\n\n---\n\n*Wondrous item, minor tier, uncommon*\nSending stones come in pairs, with each smooth stone carved to match the other so the pairing is easily recognized. While you touch one stone, you can use an action to cast the [sending](level 3 sending) spell from it. The target is the bearer of the other stone. If no creature bears the other stone, you know that fact as soon as you use the stone and don't cast the spell.\n\nOnce sending is cast through the stones, they can't be used again until the next dawn. If one of the stones in a pair is destroyed, the other one becomes nonmagical.","sources":["DoIP"]}}

I first tried to import it from the form, and under Sources I put DMG. Upon adding it to a character sheet, and then trying to open it, I got the following error:
Argument number 2 "bonusDmg" to function "json.get" must be an integer.

I also get this error if I try placing the item in a pin, and sometimes even when trying to open it in the Equipment manager. I tried importing the item with a different source (DoIP instead of DMG, just in case the acronym was tripping up the parser), both from forms and as a JSON.

I tried setting the first line of the description to Adventuring Gear. I tried removing the line mentioning it is a Wondrous item and its rarity. None of this seemed to help.

I also tried to import it into a "virgin" version ofthe 2.4 framework (one unmodified, freshly downloaded). I keep getting the error there too.

**Comment by thagrasshoppa** [comment]
I forgot to mention in the other response, I have been testing out this framework in my regular Saturday game.  I have also been giving back feedback to the Developer.  I love the framework so far, and it does many things well.  There are some issues, but we are all striving to work though them together.

**Comment by Rukbat16** [comment]
This issue was fixed by the macro changes posted in the Maptool Discord.
Apparently it was caused by the link of a spell within the item description.
For those here who do not use Discord, Rod said that he would push a new build with the fix soon.

But since I'm here, I might as well do a copy-paste of the fix:
In the Markdown macros, found on Lib:Character, Lib:Campaign, Lib:Bestiary and Lib:Notebook 
[these macros] do basically the same thing, the only difference is some reference PC tokens, other NPC tokens, so they have slight differences, anything changed in one should be changed on the other

changing [h:name=if(group3=="",group1,group3)] to [h:ContentName=if(group3=="",group1,group3)] (and 2 places where that variable is referenced) fixed it

Note by Rukbat:
you will find the piece of offending code in the section marked by

and only change the 2 occurrences of name in () - that is, leave the phrase "prop="+group2+";source=;name=" as is.
