### ISSUE TITLE
Opening "Args Dialog" from Spellcasting with source=barbarian causes error 

### ISSUE THREAD

**Issue by KyleFS** [rtakehara/5e-Framework#20]
**Describe the bug**
If you try to see spell details as a barbarian, the system fails 

**To Reproduce**
1. Create a new PC as a level 1 barbarian
2. Add spells to barbarian
3. Click on a spell to launch Args Dialog

**Expected behavior**
Args Dialog opening normally

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.5
 - Maptool: 1.7.0
 - Version 2.4.7

**Additional context**
The error occurs in the Markdown macro in the Renderer group

**Comment by rtakehara** [comment]
Oh, that apparently happens with any class that doesn't have a spellcasting ability, I will look into it

**Comment by rtakehara** [comment]
that's fixed in v2.5
