### ISSUE TITLE
Saving Throw Double Bonus

### ISSUE THREAD

**Issue by francespower** [rtakehara/5e-Framework#24]
In version 2.5, when a player sets a bonus on a saving throw, the saving throw rolls correctly from the character sheet, but adds the bonus twice when rolling from Statblock. 
I'm using MapTool version 1.7.0. 

Example: A paladin has Aura of Protection and therefore has a +4 (sample CHA modifier) to all saving throws. Therefore, at level 9 they would have a Charisma saving throw of CHA*2+proficiency. I entered proficiency for the saving throw and a +4 bonus. On the character sheet, it said there was a total of +12 to a Charisma save, and the saving throw rolled +12 from the character sheet. However, rolling this from the Statblock gave the character +16 to Charisma because it showed the +12 from the Character sheet and an additional +4 bonus added on. 

**To Reproduce**

1. Create a PC token. 
2. Open the character sheet. 
3. Select a saving throw for proficiency (I'll use strength as an example here). 
4. Add a bonus to the saving throw. 
5. Roll the saving throw from the character sheet.
6. Roll the saving throw from the statblock. 

For me, this resulted in different saving throws modifiers + bonuses from the character sheet roll versus the statblock roll. 

This is from a roll I just did using a +3 bonus for an Intelligence save with INT modifier of -5 and no proficiency:
![2 5 Saving Throw Bug](https://user-images.githubusercontent.com/69366543/89682080-2722c080-d8c4-11ea-8af8-f591656ca9d4.png)
The first roll was from Statblock, the second roll was from the character sheet. The actual correct modifier for the saving throw after the bonus should be -2. 

**Software**
 - OS: Windows 10
 - MapTool: 1.7.0
 - 5e Framework 2.5

**Additional context**
My group and I have now replicated this problem among at least 3 players on different computers, and I replicated this in 5e Framework 2.4.7 as well, except that one also rolled incorrectly in the same way from the character sheet. 

(Overall your framework has been great, thanks for the work you've done putting this together!)

**Comment by rtakehara** [comment]
Oh, this must be an old bug, I changed saving throw rolls and skill check rolls in 2.4.5 I think and since custom bonuses are very situational and rarely from level 1, that slipped

I just finished fixing it and will be online soon so I will close this issue, thanks!
