### ISSUE TITLE
Toggle Default Opacity & Player Visibility for Bestiary Tokens

### ISSUE THREAD

**Issue by TheSeize** [rtakehara/5e-Framework#27]
**Is your feature request related to a problem? Please describe.**
When putting out monsters from the bestiary they default to a low opacity and are not player visible. Even with the macro, toggling this for every single one is frustrating.

**Describe the solution you'd like**
Create setting to toggle the default opacity/visibility of tokens spawned from the bestiary.

**Describe alternatives you've considered**
Using the macro, saving all the monsters in the bestiary so I can drag/drop without using the bestiary

**Additional context**
I thought it was a bug when I first tried to use the bestiary in the newer framework, and the tokens were showing up with low opacity. The entries included that have no image (red X or generic token) also made me think that there may be a bug or I needed to redownload the framework.

**Comment by rtakehara** [comment]
Oh, this is a lack of documentation of my part, on the GM panel there is a "Show/Hide Token" (or F2) that toggles both the opacity between 40% and 100% and the player visibility between invisible and visible.

The reasoning behind the decision is because I thought it made it easier for the GM to see what is visible and what isn't to the player, but yeah, maybe I should consider including a toggle visibility on the NPC token to make it more intuitive.

You don't need to toggle them one by one, the macro will toggle all selected.

I could also include a setting to create new monsters visible, just to save time if the GM prefers them this way, though I noticed performance issues with maps with lots of visible tokens

**Comment by TheSeize** [comment]
I haven't noticed any performance issues, but that is a good note and something I will keep in mind. Do you have a sense of approximately how many visible tokens on a single map starts to cause issues?

Now that I understand the feature, that macro is very useful! I'd still prefer a setting to create new monsters visible. It would save me time and give DMs flexibility for what they are doing and how they go about running games. I did watch your video on how you build and run adventures (how I figured out this wasn't a bug and made the connection with the macro), and it is very different to my own method of building adventures and style of running.

**Comment by rtakehara** [comment]
About the performance, I am not sure what causes me problems yet, but I have some ideas.

I think tokens with VBL and light sources have a big impact on performance, many tokens with unique images also have a significant impact, Macros and properties I am unsure if they have a significant change.

Also, these don't happen on my prep work, I can load hundreds of unique tokens with macros no problem, but when I have 3 or more players connected I notice performance drops

---

About the visibility feature, I think I will make a setting to change the default behavior then!

**Comment by rtakehara** [comment]
> I thought it was a bug when I first tried to use the bestiary in the newer framework, and the tokens were showing up with low opacity. The entries included that have no image (red X or generic token) also made me think that there may be a bug or I needed to redownload the framework.

I had something about this but forgot to mention, the X means I set a image from the downloaded resources of a certain 5e tool website that you don't have, If you include that on your MapTool resources it should display properly.

And as a fun fact, the generic tokens use the Hero token for humanoids with lots of AC, Mage token as humanoids with low AC, except elves that use the Elf token, Dragons and monstrosities use the Dragon token, and beasts use the Wolf token, or the Eagle token if they can fly, and Giants and Fiends use the Troll token

**Comment by TheSeize** [comment]
> I had something about this but forgot to mention, the X means I set a image from the downloaded resources of a certain 5e tool website that you don't have, If you include that on your MapTool resources it should display properly.

What URL from 5e tools am I adding where? 

> And as a fun fact, the generic tokens use the Hero token for humanoids with lots of AC, Mage token as humanoids with low AC, except elves that use the Elf token, Dragons and monstrosities use the Dragon token, and beasts use the Wolf token, or the Eagle token if they can fly, and Giants and Fiends use the Troll token

This is another feature that read to me as a bug. Me: "Why is the wrong token showing for a lot of these?"

**Comment by thagrasshoppa** [comment]
I can see how it would seem like a bug, but it has more to do with what he
has the license to distribute...

As for the 5e.tools site I think he is talking about:

https://5e.tools/  I have seen him refer to this site, but I have also seen
him refer to other sites.

I am curious, would you be interested in collaborating on this framework in
a more organized way?

Tim

**Comment by TheSeize** [comment]
> I can see how it would seem like a bug, but it has more to do with what he
> has the license to distribute..

I get that. I am pointing this out as an opportunity for a bit of doc or UX that might prevent confusion. Big red X's and incorrect portraits are likely not going to be interpreted as features by people who go to use this regardless of why its being done that way. 

> As for the 5e.tools site I think he is talking about:
> 
> https://5e.tools/  I have seen him refer to this site, but I have also seen
> him refer to other sites.

I am very familiar with the website he is referring to, but I am not sure what exact URL I should be using and where to add it to MapTool's resources correctly to update the bestiary. 

> I am curious, would you be interested in collaborating on this framework in
> a more organized way?

I don't know what you mean by this. I am not a software developer. 

I have offered to try to help with documentation a bit, and we're trying to figure out how to go about that in the doc feature request thread.

**Comment by thagrasshoppa** [comment]
Agreed, understood, and I meant maybe we could find a common discord or the
like to coordinate efforts to document things better.

**Comment by francespower** [comment]
There's already a MapTool Discord: https://discord.gg/jRtGdw 
The #dnd5e-takahara channel exists to discuss this framework.

**Comment by rtakehara** [comment]
> I am very familiar with the website he is referring to, but I am not sure what exact URL I should be using and where to add it to MapTool's resources correctly to update the bestiary.

On that site you can download the image resources to your computer, with that downloaded, go to MapTool>File>Add Resource to Library and put the downloaded folder to the path, that should link the assets properly.

But since that site resides in a legally gray area, I agree that this solution is not ideal, I think it is possible for MapTool to detect if an asset is loaded or not, and if it isn't I could direct to the default images. But I think it's a new feature on maptool so I am not sure if it does what I think it does.

**Comment by rtakehara** [comment]
Added two options on the Settings>Display Settings, "Hide New NPCs from Players" and "Hidden Opacity", so the DM can change the default behavior, this will not change existing tokens, just new ones.

Also added a "Hide" macro on new NPC tokens.

Finally, added a code that detects if an image asset is loaded, so if an asset doesn't exist, it will display a default token instead.
