### ISSUE TITLE
Goblin missing in new version's

### ISSUE THREAD

**Issue by awingedrhino** [rtakehara/5e-Framework#29]
**Describe the bug**

**To Reproduce**
1. Go to 'Goblin in beastiary or search'
2. Click on 'Goblin'

4. See error 'Argument number 2 "status" to function "json.get" must be an integer.'

**Expected behavior**
Goblin statblock should open like other Npc's 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft
 - Maptool Version 1.7.0
 - Framework Version 2.5.2 and 2.5.1

**Additional context**
code error from chat window, nothing happens when you click on goblin

**Comment by rtakehara** [comment]
I couldn't replicate the problem both in 2.5.2 and 2.5.1, but I just released 2.5.3, see if the problem persists, alternatively, I uploaded the exported compendium with SRD content that you can import into the framework, download it [here](https://github.com/rtakehara/5e-Framework/blob/master/Resources/SRD%20Compendium.json).
