### ISSUE TITLE
Problem with hit dice in creation wizard

### ISSUE THREAD

**Issue by chiappe666** [rtakehara/5e-Framework#31]
**Describe the bug**
in the creation wizard when leveling up, in the Details sections triying to roll the hit dice gives the following error.

java.lang.NullPointerException error executing expression classes=getLibProperty("Class&Level","Lib:"+tokenName).

**To Reproduce**
1. Go to Player Menu
2. Click on level up
3. Go throught the wizard up to the details section
4. Click on the dice (macro link)
5. See  "java.lang.NullPointerException error executing expression classes=getLibProperty("Class&Level","Lib:"+tokenName)" on chat

**Expected behavior**
See the dice roll on the chat

**Desktop (please complete the following information):**
 - OS: Win10
 - Maptool Version v1.7.0
 - Framework Version 2.5.3

**Comment by rtakehara** [comment]
fixed in 2.5.4

related to that, on character creation, now you can set your HP to be the dicevalue+con (eg. 12+con)
