### ISSUE TITLE
(Bug) Lantern, Hooded does not emanate light when chosen from the Light macro

### ISSUE THREAD

**Issue by spacechonk** [rtakehara/5e-Framework#32]
**Describe the bug**
The Lantern, Hooded (aka Hooded Lantern ) does not emit light when selected from the other macros panel. It's also one item but shows up twice, technically.

**To Reproduce**
1. Select a player character token
2. Click on "Light" in the Selected window
3. Selected "Lantern" or "Hooded - 30"

**Expected behavior**
I expect a light source to emanate from the selected token that casts bright light for 30 ft and dim light for an additional 30 ft

**Screenshots**
![Hooded AND Lantern in code](https://imgur.com/nMcQJwI) Hooded AND Lantern in code
![Twice](https://imgur.com/nMcQJwI)

**Desktop (please complete the following information):**
 - Windows 10
 - Maptool Version 1.7.0
 - Framework Version 2.5.3

**Additional context**
If you right click on a token, select light sources, click on d20, and pick the "lantern, hooded - 30" option - light will be cast from the token

edit: Not sure why the screenshots aren't working and don't want to work. But here's a link to imgur with the screenshot. https://imgur.com/a/vrtom7k

**Comment by rtakehara** [comment]
there was a wrong bit on the code, fixed on 2.5.4
